FROM node:latest

COPY package.json .
COPY pnpm-lock.yaml .

RUN ["npm", "install", "pnpm", "-g"]
RUN ["pnpm", "install", "--frozen-lockfile", "--prod"]

COPY src/tsconfig.json src/tsconfig.json
COPY src/server.ts src/server.ts

ENV NODE_ENV "production"

CMD [ "npx", "ts-node", "src/server.ts" ]

EXPOSE 3001