FROM node:lts

WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .

RUN ["npm", "install", "pnpm", "-g"]
RUN ["pnpm", "install", "--frozen-lockfile", "--prod"]

COPY src/tsconfig.json tsconfig.json
COPY src/tsconfig-server.json tsconfig-server.json
COPY src/server.ts server.ts  

RUN [ "npx", "tsc", "-p", "tsconfig-server.json"]

ENV NODE_ENV="production"

EXPOSE 3001

CMD [ "node", "server.js" ]

