-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."logs" add column "consumed" boolean
--  not null default 'true';
